# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: serverless-stripe-backend

# Configuration variables
custom:
  secrets: ${file(secrets.json)}

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs8.10
  # stage: prod
  stage: dev
  # profile: personal
  # region: ap-southeast-1
  environment:
    STRIPE_SECRET_KEY: ${self:custom.secrets.stripeSecretKey} # Stripe secret API key
    AUTH_CLIENT_ID: ${self:custom.secrets.authClientId} # Stripe secret API key
    AUTH_CLIENT_SECRET: ${self:custom.secrets.authClientSecret} # Stripe secret API key

# The `functions` block defines what code to deploy
functions:
  createUser:
    handler: functions/createUser.handler
    # The `events` block defines how to trigger the handler.createCharge code
    events:
      - http:
          path: users
          method: post
          cors: true
  createCharge:
    handler: functions/createCharge.handler
    # The `events` block defines how to trigger the handler.createCharge code
    events:
      - http:
          path: charges
          method: post
          cors: true
  createSource:
    handler: functions/createSource.handler
    # The `events` block defines how to trigger the handler.createSource code
    events:
      - http:
          path: sources
          method: post
          cors: true
  sourceStatus:
    handler: functions/checkSource.handler
    # The `events` block defines how to trigger the handler.createSource code
    events:
      - http:
          path: status
          method: get
          cors: true
